apiVersion: v1
kind: Namespace
metadata:
  name: mom-system
  labels:
    app.kubernetes.io/part-of: industrial-mom
---
apiVersion: v1
kind: Namespace
metadata:
  name: mom-data
  labels:
    app.kubernetes.io/part-of: industrial-mom
---
apiVersion: v1
kind: Namespace
metadata:
  name: mom-messaging
  labels:
    app.kubernetes.io/part-of: industrial-mom
---
apiVersion: v1
kind: Namespace
metadata:
  name: mom-observability
  labels:
    app.kubernetes.io/part-of: industrial-mom
---
apiVersion: v1
kind: Namespace
metadata:
  name: mom-apps
  labels:
    app.kubernetes.io/part-of: industrial-mom
